from os import getenv


CIRCUIT_BREAKER_FLAG = getenv("CIRCUIT_BREAKER_FLAG")

CELERY_BROKER_URL = getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = CELERY_TASK_SERIALIZER
CELERY_REDIS_MAX_CONNECTIONS = 5
CELERY_TASK_LIST = ["src.blueprints.main.tasks"]
